### ISSUE TITLE
UUF Solver: Bogus link in resources & references of response

### ISSUE THREAD

**Issue by anandmeg** [jonburchel/DeepSearchAI#18]
**Describe the bug**
Bogus links are sometimes returned in responses.

**To Reproduce**
1. Go to UUF Solver tool (https://uuf-solver.azurewebsites.net/)
2. Enter following details in the query textbox
     **Title:
     Install Visual Studio and choose your preferred features | Microsoft Learn

     Verbatim:
     Need to install product key not explained**
4. Enter to start generating a response
5. Returned response contains broken link in "Additional Resources" and "References" at the end of the response

**Result:**
Bogus link 
[How to activate Visual Studio](https://learn.microsoft.com/en-us/visualstudio/install/activate-visual-studio?view=vs-2022)

**Expected behavior**
No invalid links

Response from UUF Solver:
## IMPORTANT 
Always validate the ground truth of any answer before using it in your work, and use the ai-usage:ai-assisted metadata tag in any article you update from this tool, per the [guidance in the Docs Contributors Guide](https://review.learn.microsoft.com/en-us/help/contribute/guidance-for-ai-generated-content?branch=main#how-to-add-ai-usage-metadata-to-ai-generated-content).

## Article
[Install Visual Studio and choose your preferred features | Microsoft Learn](https://learn.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2022)

## Feedback
Need to install product key not explained

#### Adding a Section on Installing a Product Key

To address the feedback, a new section should be added to the article explaining how to install a product key in Visual Studio. This section can be placed after the installation steps or in a relevant section where licensing is discussed.

#### Proposed Section: Installing a Product Key in Visual Studio

**Installing a Product Key in Visual Studio**

1. **Open Visual Studio**: Launch Visual Studio from your Start menu or desktop shortcut.
2. **Navigate to the Help Menu**: In the top menu bar, click on `Help`.
3. **Select 'Register Product'**: From the dropdown menu, select `Register Product`.
4. **Enter Your Product Key**: In the dialog box that appears, enter your product key in the provided field.
5. **Activate**: Click on the `Activate` button to complete the process.

**Note**: If you have a subscription, you might not need to enter a product key. Visual Studio can automatically detect your subscription when you sign in with your Microsoft account.

#### Visual Guide

To make the process clearer, consider adding screenshots of each step. This visual aid can help users follow along more easily.

#### Additional Resources

- [How to activate Visual Studio](https://learn.microsoft.com/en-us/visualstudio/install/activate-visual-studio?view=vs-2022)
- [Visual Studio Subscriptions](https://visualstudio.microsoft.com/subscriptions/)

## References
1. **/**
2. [Visual Studio Subscriptions](https://visualstudio.microsoft.com/subscriptions/)
3. [Microsoft Visual Studio Documentation](https://learn.microsoft.com/en-us/visualstudio/?view=vs-2022)

**Comment by jonburchel** [comment]
Thanks @anandmeg for actively participating! We are tracking these via the feedback mechanism, since they might occur occasionally and it lets us analyze all of them to see if some patterns might suggest problems in our prompts, etc. I will close this one out since it is covered by the feedback tracking mechanism. For issues like error messages or for new features, we can continue submitting those here, or in other avenues internally too.
